// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHlQxAbmnDrhPpNfOWSpCKyxhpHw5rXYg',
    appId: '1:834673530229:web:cc5c0783cffbd580c0af3c',
    messagingSenderId: '834673530229',
    projectId: 'malak-isi-project',
    authDomain: 'malak-isi-project.firebaseapp.com',
    storageBucket: 'malak-isi-project.appspot.com',
    measurementId: 'G-NMMT6KYK0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFwER4YfGhlUGd3V03pBon_hNWUYCGNck',
    appId: '1:834673530229:android:de2803b985f0e683c0af3c',
    messagingSenderId: '834673530229',
    projectId: 'malak-isi-project',
    storageBucket: 'malak-isi-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIAAcKX1shOw8-BlvrappxBK9zHLNEfA',
    appId: '1:834673530229:ios:d12f7a11ec9d4630c0af3c',
    messagingSenderId: '834673530229',
    projectId: 'malak-isi-project',
    storageBucket: 'malak-isi-project.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAIAAcKX1shOw8-BlvrappxBK9zHLNEfA',
    appId: '1:834673530229:ios:d12f7a11ec9d4630c0af3c',
    messagingSenderId: '834673530229',
    projectId: 'malak-isi-project',
    storageBucket: 'malak-isi-project.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHlQxAbmnDrhPpNfOWSpCKyxhpHw5rXYg',
    appId: '1:834673530229:web:1ef214280897e938c0af3c',
    messagingSenderId: '834673530229',
    projectId: 'malak-isi-project',
    authDomain: 'malak-isi-project.firebaseapp.com',
    storageBucket: 'malak-isi-project.appspot.com',
    measurementId: 'G-7K9LBP69KW',
  );

}